/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 9.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RestCreateBranchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestCreateBranchRequest{}

// RestCreateBranchRequest struct for RestCreateBranchRequest
type RestCreateBranchRequest struct {
	Message *string `json:"message,omitempty"`
	Name *string `json:"name,omitempty"`
	StartPoint *string `json:"startPoint,omitempty"`
}

// NewRestCreateBranchRequest instantiates a new RestCreateBranchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestCreateBranchRequest() *RestCreateBranchRequest {
	this := RestCreateBranchRequest{}
	return &this
}

// NewRestCreateBranchRequestWithDefaults instantiates a new RestCreateBranchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestCreateBranchRequestWithDefaults() *RestCreateBranchRequest {
	this := RestCreateBranchRequest{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *RestCreateBranchRequest) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestCreateBranchRequest) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *RestCreateBranchRequest) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *RestCreateBranchRequest) SetMessage(v string) {
	o.Message = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RestCreateBranchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestCreateBranchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RestCreateBranchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RestCreateBranchRequest) SetName(v string) {
	o.Name = &v
}

// GetStartPoint returns the StartPoint field value if set, zero value otherwise.
func (o *RestCreateBranchRequest) GetStartPoint() string {
	if o == nil || IsNil(o.StartPoint) {
		var ret string
		return ret
	}
	return *o.StartPoint
}

// GetStartPointOk returns a tuple with the StartPoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestCreateBranchRequest) GetStartPointOk() (*string, bool) {
	if o == nil || IsNil(o.StartPoint) {
		return nil, false
	}
	return o.StartPoint, true
}

// HasStartPoint returns a boolean if a field has been set.
func (o *RestCreateBranchRequest) HasStartPoint() bool {
	if o != nil && !IsNil(o.StartPoint) {
		return true
	}

	return false
}

// SetStartPoint gets a reference to the given string and assigns it to the StartPoint field.
func (o *RestCreateBranchRequest) SetStartPoint(v string) {
	o.StartPoint = &v
}

func (o RestCreateBranchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestCreateBranchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.StartPoint) {
		toSerialize["startPoint"] = o.StartPoint
	}
	return toSerialize, nil
}

type NullableRestCreateBranchRequest struct {
	value *RestCreateBranchRequest
	isSet bool
}

func (v NullableRestCreateBranchRequest) Get() *RestCreateBranchRequest {
	return v.value
}

func (v *NullableRestCreateBranchRequest) Set(val *RestCreateBranchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRestCreateBranchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRestCreateBranchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestCreateBranchRequest(val *RestCreateBranchRequest) *NullableRestCreateBranchRequest {
	return &NullableRestCreateBranchRequest{value: val, isSet: true}
}

func (v NullableRestCreateBranchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestCreateBranchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


