/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 9.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TotpRecoveryCodeDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TotpRecoveryCodeDTO{}

// TotpRecoveryCodeDTO struct for TotpRecoveryCodeDTO
type TotpRecoveryCodeDTO struct {
	RecoveryCode *string `json:"recoveryCode,omitempty"`
}

// NewTotpRecoveryCodeDTO instantiates a new TotpRecoveryCodeDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTotpRecoveryCodeDTO() *TotpRecoveryCodeDTO {
	this := TotpRecoveryCodeDTO{}
	return &this
}

// NewTotpRecoveryCodeDTOWithDefaults instantiates a new TotpRecoveryCodeDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTotpRecoveryCodeDTOWithDefaults() *TotpRecoveryCodeDTO {
	this := TotpRecoveryCodeDTO{}
	return &this
}

// GetRecoveryCode returns the RecoveryCode field value if set, zero value otherwise.
func (o *TotpRecoveryCodeDTO) GetRecoveryCode() string {
	if o == nil || IsNil(o.RecoveryCode) {
		var ret string
		return ret
	}
	return *o.RecoveryCode
}

// GetRecoveryCodeOk returns a tuple with the RecoveryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TotpRecoveryCodeDTO) GetRecoveryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.RecoveryCode) {
		return nil, false
	}
	return o.RecoveryCode, true
}

// HasRecoveryCode returns a boolean if a field has been set.
func (o *TotpRecoveryCodeDTO) HasRecoveryCode() bool {
	if o != nil && !IsNil(o.RecoveryCode) {
		return true
	}

	return false
}

// SetRecoveryCode gets a reference to the given string and assigns it to the RecoveryCode field.
func (o *TotpRecoveryCodeDTO) SetRecoveryCode(v string) {
	o.RecoveryCode = &v
}

func (o TotpRecoveryCodeDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TotpRecoveryCodeDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RecoveryCode) {
		toSerialize["recoveryCode"] = o.RecoveryCode
	}
	return toSerialize, nil
}

type NullableTotpRecoveryCodeDTO struct {
	value *TotpRecoveryCodeDTO
	isSet bool
}

func (v NullableTotpRecoveryCodeDTO) Get() *TotpRecoveryCodeDTO {
	return v.value
}

func (v *NullableTotpRecoveryCodeDTO) Set(val *TotpRecoveryCodeDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableTotpRecoveryCodeDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableTotpRecoveryCodeDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTotpRecoveryCodeDTO(val *TotpRecoveryCodeDTO) *NullableTotpRecoveryCodeDTO {
	return &NullableTotpRecoveryCodeDTO{value: val, isSet: true}
}

func (v NullableTotpRecoveryCodeDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTotpRecoveryCodeDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


