/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 9.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RestRefMatcherType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestRefMatcherType{}

// RestRefMatcherType struct for RestRefMatcherType
type RestRefMatcherType struct {
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewRestRefMatcherType instantiates a new RestRefMatcherType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestRefMatcherType() *RestRefMatcherType {
	this := RestRefMatcherType{}
	return &this
}

// NewRestRefMatcherTypeWithDefaults instantiates a new RestRefMatcherType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestRefMatcherTypeWithDefaults() *RestRefMatcherType {
	this := RestRefMatcherType{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RestRefMatcherType) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestRefMatcherType) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RestRefMatcherType) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *RestRefMatcherType) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RestRefMatcherType) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestRefMatcherType) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RestRefMatcherType) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RestRefMatcherType) SetName(v string) {
	o.Name = &v
}

func (o RestRefMatcherType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestRefMatcherType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableRestRefMatcherType struct {
	value *RestRefMatcherType
	isSet bool
}

func (v NullableRestRefMatcherType) Get() *RestRefMatcherType {
	return v.value
}

func (v *NullableRestRefMatcherType) Set(val *RestRefMatcherType) {
	v.value = val
	v.isSet = true
}

func (v NullableRestRefMatcherType) IsSet() bool {
	return v.isSet
}

func (v *NullableRestRefMatcherType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestRefMatcherType(val *RestRefMatcherType) *NullableRestRefMatcherType {
	return &NullableRestRefMatcherType{value: val, isSet: true}
}

func (v NullableRestRefMatcherType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestRefMatcherType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


