/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 9.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PullRequestParticipant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PullRequestParticipant{}

// PullRequestParticipant struct for PullRequestParticipant
type PullRequestParticipant struct {
	Approved *bool `json:"approved,omitempty"`
	LastReviewedCommit *string `json:"lastReviewedCommit,omitempty"`
	PullRequest *PullRequest `json:"pullRequest,omitempty"`
	Role *string `json:"role,omitempty"`
	Status *string `json:"status,omitempty"`
	User *ApplicationUser `json:"user,omitempty"`
}

// NewPullRequestParticipant instantiates a new PullRequestParticipant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPullRequestParticipant() *PullRequestParticipant {
	this := PullRequestParticipant{}
	return &this
}

// NewPullRequestParticipantWithDefaults instantiates a new PullRequestParticipant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPullRequestParticipantWithDefaults() *PullRequestParticipant {
	this := PullRequestParticipant{}
	return &this
}

// GetApproved returns the Approved field value if set, zero value otherwise.
func (o *PullRequestParticipant) GetApproved() bool {
	if o == nil || IsNil(o.Approved) {
		var ret bool
		return ret
	}
	return *o.Approved
}

// GetApprovedOk returns a tuple with the Approved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PullRequestParticipant) GetApprovedOk() (*bool, bool) {
	if o == nil || IsNil(o.Approved) {
		return nil, false
	}
	return o.Approved, true
}

// HasApproved returns a boolean if a field has been set.
func (o *PullRequestParticipant) HasApproved() bool {
	if o != nil && !IsNil(o.Approved) {
		return true
	}

	return false
}

// SetApproved gets a reference to the given bool and assigns it to the Approved field.
func (o *PullRequestParticipant) SetApproved(v bool) {
	o.Approved = &v
}

// GetLastReviewedCommit returns the LastReviewedCommit field value if set, zero value otherwise.
func (o *PullRequestParticipant) GetLastReviewedCommit() string {
	if o == nil || IsNil(o.LastReviewedCommit) {
		var ret string
		return ret
	}
	return *o.LastReviewedCommit
}

// GetLastReviewedCommitOk returns a tuple with the LastReviewedCommit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PullRequestParticipant) GetLastReviewedCommitOk() (*string, bool) {
	if o == nil || IsNil(o.LastReviewedCommit) {
		return nil, false
	}
	return o.LastReviewedCommit, true
}

// HasLastReviewedCommit returns a boolean if a field has been set.
func (o *PullRequestParticipant) HasLastReviewedCommit() bool {
	if o != nil && !IsNil(o.LastReviewedCommit) {
		return true
	}

	return false
}

// SetLastReviewedCommit gets a reference to the given string and assigns it to the LastReviewedCommit field.
func (o *PullRequestParticipant) SetLastReviewedCommit(v string) {
	o.LastReviewedCommit = &v
}

// GetPullRequest returns the PullRequest field value if set, zero value otherwise.
func (o *PullRequestParticipant) GetPullRequest() PullRequest {
	if o == nil || IsNil(o.PullRequest) {
		var ret PullRequest
		return ret
	}
	return *o.PullRequest
}

// GetPullRequestOk returns a tuple with the PullRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PullRequestParticipant) GetPullRequestOk() (*PullRequest, bool) {
	if o == nil || IsNil(o.PullRequest) {
		return nil, false
	}
	return o.PullRequest, true
}

// HasPullRequest returns a boolean if a field has been set.
func (o *PullRequestParticipant) HasPullRequest() bool {
	if o != nil && !IsNil(o.PullRequest) {
		return true
	}

	return false
}

// SetPullRequest gets a reference to the given PullRequest and assigns it to the PullRequest field.
func (o *PullRequestParticipant) SetPullRequest(v PullRequest) {
	o.PullRequest = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *PullRequestParticipant) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PullRequestParticipant) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *PullRequestParticipant) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *PullRequestParticipant) SetRole(v string) {
	o.Role = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PullRequestParticipant) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PullRequestParticipant) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PullRequestParticipant) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PullRequestParticipant) SetStatus(v string) {
	o.Status = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *PullRequestParticipant) GetUser() ApplicationUser {
	if o == nil || IsNil(o.User) {
		var ret ApplicationUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PullRequestParticipant) GetUserOk() (*ApplicationUser, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *PullRequestParticipant) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given ApplicationUser and assigns it to the User field.
func (o *PullRequestParticipant) SetUser(v ApplicationUser) {
	o.User = &v
}

func (o PullRequestParticipant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PullRequestParticipant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Approved) {
		toSerialize["approved"] = o.Approved
	}
	if !IsNil(o.LastReviewedCommit) {
		toSerialize["lastReviewedCommit"] = o.LastReviewedCommit
	}
	if !IsNil(o.PullRequest) {
		toSerialize["pullRequest"] = o.PullRequest
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	return toSerialize, nil
}

type NullablePullRequestParticipant struct {
	value *PullRequestParticipant
	isSet bool
}

func (v NullablePullRequestParticipant) Get() *PullRequestParticipant {
	return v.value
}

func (v *NullablePullRequestParticipant) Set(val *PullRequestParticipant) {
	v.value = val
	v.isSet = true
}

func (v NullablePullRequestParticipant) IsSet() bool {
	return v.isSet
}

func (v *NullablePullRequestParticipant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePullRequestParticipant(val *PullRequestParticipant) *NullablePullRequestParticipant {
	return &NullablePullRequestParticipant{value: val, isSet: true}
}

func (v NullablePullRequestParticipant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePullRequestParticipant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


