/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 9.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AdminPasswordUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminPasswordUpdate{}

// AdminPasswordUpdate struct for AdminPasswordUpdate
type AdminPasswordUpdate struct {
	Name *string `json:"name,omitempty"`
	Password *string `json:"password,omitempty"`
	PasswordConfirm *string `json:"passwordConfirm,omitempty"`
}

// NewAdminPasswordUpdate instantiates a new AdminPasswordUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminPasswordUpdate() *AdminPasswordUpdate {
	this := AdminPasswordUpdate{}
	return &this
}

// NewAdminPasswordUpdateWithDefaults instantiates a new AdminPasswordUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminPasswordUpdateWithDefaults() *AdminPasswordUpdate {
	this := AdminPasswordUpdate{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AdminPasswordUpdate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminPasswordUpdate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AdminPasswordUpdate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AdminPasswordUpdate) SetName(v string) {
	o.Name = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *AdminPasswordUpdate) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminPasswordUpdate) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *AdminPasswordUpdate) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *AdminPasswordUpdate) SetPassword(v string) {
	o.Password = &v
}

// GetPasswordConfirm returns the PasswordConfirm field value if set, zero value otherwise.
func (o *AdminPasswordUpdate) GetPasswordConfirm() string {
	if o == nil || IsNil(o.PasswordConfirm) {
		var ret string
		return ret
	}
	return *o.PasswordConfirm
}

// GetPasswordConfirmOk returns a tuple with the PasswordConfirm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminPasswordUpdate) GetPasswordConfirmOk() (*string, bool) {
	if o == nil || IsNil(o.PasswordConfirm) {
		return nil, false
	}
	return o.PasswordConfirm, true
}

// HasPasswordConfirm returns a boolean if a field has been set.
func (o *AdminPasswordUpdate) HasPasswordConfirm() bool {
	if o != nil && !IsNil(o.PasswordConfirm) {
		return true
	}

	return false
}

// SetPasswordConfirm gets a reference to the given string and assigns it to the PasswordConfirm field.
func (o *AdminPasswordUpdate) SetPasswordConfirm(v string) {
	o.PasswordConfirm = &v
}

func (o AdminPasswordUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminPasswordUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.PasswordConfirm) {
		toSerialize["passwordConfirm"] = o.PasswordConfirm
	}
	return toSerialize, nil
}

type NullableAdminPasswordUpdate struct {
	value *AdminPasswordUpdate
	isSet bool
}

func (v NullableAdminPasswordUpdate) Get() *AdminPasswordUpdate {
	return v.value
}

func (v *NullableAdminPasswordUpdate) Set(val *AdminPasswordUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminPasswordUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminPasswordUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminPasswordUpdate(val *AdminPasswordUpdate) *NullableAdminPasswordUpdate {
	return &NullableAdminPasswordUpdate{value: val, isSet: true}
}

func (v NullableAdminPasswordUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminPasswordUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


