/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 9.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RestPullRequestParticipant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestPullRequestParticipant{}

// RestPullRequestParticipant struct for RestPullRequestParticipant
type RestPullRequestParticipant struct {
	Approved *bool `json:"approved,omitempty"`
	LastReviewedCommit *string `json:"lastReviewedCommit,omitempty"`
	Role *string `json:"role,omitempty"`
	Status *string `json:"status,omitempty"`
	User *RestCommentAnchorPullRequestAuthorUser `json:"user,omitempty"`
}

// NewRestPullRequestParticipant instantiates a new RestPullRequestParticipant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestPullRequestParticipant() *RestPullRequestParticipant {
	this := RestPullRequestParticipant{}
	return &this
}

// NewRestPullRequestParticipantWithDefaults instantiates a new RestPullRequestParticipant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestPullRequestParticipantWithDefaults() *RestPullRequestParticipant {
	this := RestPullRequestParticipant{}
	return &this
}

// GetApproved returns the Approved field value if set, zero value otherwise.
func (o *RestPullRequestParticipant) GetApproved() bool {
	if o == nil || IsNil(o.Approved) {
		var ret bool
		return ret
	}
	return *o.Approved
}

// GetApprovedOk returns a tuple with the Approved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestPullRequestParticipant) GetApprovedOk() (*bool, bool) {
	if o == nil || IsNil(o.Approved) {
		return nil, false
	}
	return o.Approved, true
}

// HasApproved returns a boolean if a field has been set.
func (o *RestPullRequestParticipant) HasApproved() bool {
	if o != nil && !IsNil(o.Approved) {
		return true
	}

	return false
}

// SetApproved gets a reference to the given bool and assigns it to the Approved field.
func (o *RestPullRequestParticipant) SetApproved(v bool) {
	o.Approved = &v
}

// GetLastReviewedCommit returns the LastReviewedCommit field value if set, zero value otherwise.
func (o *RestPullRequestParticipant) GetLastReviewedCommit() string {
	if o == nil || IsNil(o.LastReviewedCommit) {
		var ret string
		return ret
	}
	return *o.LastReviewedCommit
}

// GetLastReviewedCommitOk returns a tuple with the LastReviewedCommit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestPullRequestParticipant) GetLastReviewedCommitOk() (*string, bool) {
	if o == nil || IsNil(o.LastReviewedCommit) {
		return nil, false
	}
	return o.LastReviewedCommit, true
}

// HasLastReviewedCommit returns a boolean if a field has been set.
func (o *RestPullRequestParticipant) HasLastReviewedCommit() bool {
	if o != nil && !IsNil(o.LastReviewedCommit) {
		return true
	}

	return false
}

// SetLastReviewedCommit gets a reference to the given string and assigns it to the LastReviewedCommit field.
func (o *RestPullRequestParticipant) SetLastReviewedCommit(v string) {
	o.LastReviewedCommit = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *RestPullRequestParticipant) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestPullRequestParticipant) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *RestPullRequestParticipant) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *RestPullRequestParticipant) SetRole(v string) {
	o.Role = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RestPullRequestParticipant) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestPullRequestParticipant) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RestPullRequestParticipant) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *RestPullRequestParticipant) SetStatus(v string) {
	o.Status = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *RestPullRequestParticipant) GetUser() RestCommentAnchorPullRequestAuthorUser {
	if o == nil || IsNil(o.User) {
		var ret RestCommentAnchorPullRequestAuthorUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestPullRequestParticipant) GetUserOk() (*RestCommentAnchorPullRequestAuthorUser, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *RestPullRequestParticipant) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given RestCommentAnchorPullRequestAuthorUser and assigns it to the User field.
func (o *RestPullRequestParticipant) SetUser(v RestCommentAnchorPullRequestAuthorUser) {
	o.User = &v
}

func (o RestPullRequestParticipant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestPullRequestParticipant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Approved) {
		toSerialize["approved"] = o.Approved
	}
	if !IsNil(o.LastReviewedCommit) {
		toSerialize["lastReviewedCommit"] = o.LastReviewedCommit
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	return toSerialize, nil
}

type NullableRestPullRequestParticipant struct {
	value *RestPullRequestParticipant
	isSet bool
}

func (v NullableRestPullRequestParticipant) Get() *RestPullRequestParticipant {
	return v.value
}

func (v *NullableRestPullRequestParticipant) Set(val *RestPullRequestParticipant) {
	v.value = val
	v.isSet = true
}

func (v NullableRestPullRequestParticipant) IsSet() bool {
	return v.isSet
}

func (v *NullableRestPullRequestParticipant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestPullRequestParticipant(val *RestPullRequestParticipant) *NullableRestPullRequestParticipant {
	return &NullableRestPullRequestParticipant{value: val, isSet: true}
}

func (v NullableRestPullRequestParticipant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestPullRequestParticipant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


