/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 9.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RestLogLevel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestLogLevel{}

// RestLogLevel struct for RestLogLevel
type RestLogLevel struct {
	LogLevel *string `json:"logLevel,omitempty"`
}

// NewRestLogLevel instantiates a new RestLogLevel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestLogLevel() *RestLogLevel {
	this := RestLogLevel{}
	return &this
}

// NewRestLogLevelWithDefaults instantiates a new RestLogLevel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestLogLevelWithDefaults() *RestLogLevel {
	this := RestLogLevel{}
	return &this
}

// GetLogLevel returns the LogLevel field value if set, zero value otherwise.
func (o *RestLogLevel) GetLogLevel() string {
	if o == nil || IsNil(o.LogLevel) {
		var ret string
		return ret
	}
	return *o.LogLevel
}

// GetLogLevelOk returns a tuple with the LogLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestLogLevel) GetLogLevelOk() (*string, bool) {
	if o == nil || IsNil(o.LogLevel) {
		return nil, false
	}
	return o.LogLevel, true
}

// HasLogLevel returns a boolean if a field has been set.
func (o *RestLogLevel) HasLogLevel() bool {
	if o != nil && !IsNil(o.LogLevel) {
		return true
	}

	return false
}

// SetLogLevel gets a reference to the given string and assigns it to the LogLevel field.
func (o *RestLogLevel) SetLogLevel(v string) {
	o.LogLevel = &v
}

func (o RestLogLevel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestLogLevel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LogLevel) {
		toSerialize["logLevel"] = o.LogLevel
	}
	return toSerialize, nil
}

type NullableRestLogLevel struct {
	value *RestLogLevel
	isSet bool
}

func (v NullableRestLogLevel) Get() *RestLogLevel {
	return v.value
}

func (v *NullableRestLogLevel) Set(val *RestLogLevel) {
	v.value = val
	v.isSet = true
}

func (v NullableRestLogLevel) IsSet() bool {
	return v.isSet
}

func (v *NullableRestLogLevel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestLogLevel(val *RestLogLevel) *NullableRestLogLevel {
	return &NullableRestLogLevel{value: val, isSet: true}
}

func (v NullableRestLogLevel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestLogLevel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


