/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 9.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TotpElevationRestDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TotpElevationRestDTO{}

// TotpElevationRestDTO struct for TotpElevationRestDTO
type TotpElevationRestDTO struct {
	TotpCode *string `json:"totpCode,omitempty"`
}

// NewTotpElevationRestDTO instantiates a new TotpElevationRestDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTotpElevationRestDTO() *TotpElevationRestDTO {
	this := TotpElevationRestDTO{}
	return &this
}

// NewTotpElevationRestDTOWithDefaults instantiates a new TotpElevationRestDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTotpElevationRestDTOWithDefaults() *TotpElevationRestDTO {
	this := TotpElevationRestDTO{}
	return &this
}

// GetTotpCode returns the TotpCode field value if set, zero value otherwise.
func (o *TotpElevationRestDTO) GetTotpCode() string {
	if o == nil || IsNil(o.TotpCode) {
		var ret string
		return ret
	}
	return *o.TotpCode
}

// GetTotpCodeOk returns a tuple with the TotpCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TotpElevationRestDTO) GetTotpCodeOk() (*string, bool) {
	if o == nil || IsNil(o.TotpCode) {
		return nil, false
	}
	return o.TotpCode, true
}

// HasTotpCode returns a boolean if a field has been set.
func (o *TotpElevationRestDTO) HasTotpCode() bool {
	if o != nil && !IsNil(o.TotpCode) {
		return true
	}

	return false
}

// SetTotpCode gets a reference to the given string and assigns it to the TotpCode field.
func (o *TotpElevationRestDTO) SetTotpCode(v string) {
	o.TotpCode = &v
}

func (o TotpElevationRestDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TotpElevationRestDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotpCode) {
		toSerialize["totpCode"] = o.TotpCode
	}
	return toSerialize, nil
}

type NullableTotpElevationRestDTO struct {
	value *TotpElevationRestDTO
	isSet bool
}

func (v NullableTotpElevationRestDTO) Get() *TotpElevationRestDTO {
	return v.value
}

func (v *NullableTotpElevationRestDTO) Set(val *TotpElevationRestDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableTotpElevationRestDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableTotpElevationRestDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTotpElevationRestDTO(val *TotpElevationRestDTO) *NullableTotpElevationRestDTO {
	return &NullableTotpElevationRestDTO{value: val, isSet: true}
}

func (v NullableTotpElevationRestDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTotpElevationRestDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


