/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 9.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GroupPickerContext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupPickerContext{}

// GroupPickerContext struct for GroupPickerContext
type GroupPickerContext struct {
	Context *string `json:"context,omitempty"`
	ItemName *string `json:"itemName,omitempty"`
}

// NewGroupPickerContext instantiates a new GroupPickerContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupPickerContext() *GroupPickerContext {
	this := GroupPickerContext{}
	return &this
}

// NewGroupPickerContextWithDefaults instantiates a new GroupPickerContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupPickerContextWithDefaults() *GroupPickerContext {
	this := GroupPickerContext{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *GroupPickerContext) GetContext() string {
	if o == nil || IsNil(o.Context) {
		var ret string
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupPickerContext) GetContextOk() (*string, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *GroupPickerContext) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given string and assigns it to the Context field.
func (o *GroupPickerContext) SetContext(v string) {
	o.Context = &v
}

// GetItemName returns the ItemName field value if set, zero value otherwise.
func (o *GroupPickerContext) GetItemName() string {
	if o == nil || IsNil(o.ItemName) {
		var ret string
		return ret
	}
	return *o.ItemName
}

// GetItemNameOk returns a tuple with the ItemName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupPickerContext) GetItemNameOk() (*string, bool) {
	if o == nil || IsNil(o.ItemName) {
		return nil, false
	}
	return o.ItemName, true
}

// HasItemName returns a boolean if a field has been set.
func (o *GroupPickerContext) HasItemName() bool {
	if o != nil && !IsNil(o.ItemName) {
		return true
	}

	return false
}

// SetItemName gets a reference to the given string and assigns it to the ItemName field.
func (o *GroupPickerContext) SetItemName(v string) {
	o.ItemName = &v
}

func (o GroupPickerContext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupPickerContext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.ItemName) {
		toSerialize["itemName"] = o.ItemName
	}
	return toSerialize, nil
}

type NullableGroupPickerContext struct {
	value *GroupPickerContext
	isSet bool
}

func (v NullableGroupPickerContext) Get() *GroupPickerContext {
	return v.value
}

func (v *NullableGroupPickerContext) Set(val *GroupPickerContext) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupPickerContext) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupPickerContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupPickerContext(val *GroupPickerContext) *NullableGroupPickerContext {
	return &NullableGroupPickerContext{value: val, isSet: true}
}

func (v NullableGroupPickerContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupPickerContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


