/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 9.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RestCommitMessageSuggestion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestCommitMessageSuggestion{}

// RestCommitMessageSuggestion struct for RestCommitMessageSuggestion
type RestCommitMessageSuggestion struct {
	Body *string `json:"body,omitempty"`
	Title *string `json:"title,omitempty"`
}

// NewRestCommitMessageSuggestion instantiates a new RestCommitMessageSuggestion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestCommitMessageSuggestion() *RestCommitMessageSuggestion {
	this := RestCommitMessageSuggestion{}
	return &this
}

// NewRestCommitMessageSuggestionWithDefaults instantiates a new RestCommitMessageSuggestion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestCommitMessageSuggestionWithDefaults() *RestCommitMessageSuggestion {
	this := RestCommitMessageSuggestion{}
	return &this
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *RestCommitMessageSuggestion) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestCommitMessageSuggestion) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *RestCommitMessageSuggestion) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *RestCommitMessageSuggestion) SetBody(v string) {
	o.Body = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *RestCommitMessageSuggestion) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestCommitMessageSuggestion) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *RestCommitMessageSuggestion) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *RestCommitMessageSuggestion) SetTitle(v string) {
	o.Title = &v
}

func (o RestCommitMessageSuggestion) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestCommitMessageSuggestion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	return toSerialize, nil
}

type NullableRestCommitMessageSuggestion struct {
	value *RestCommitMessageSuggestion
	isSet bool
}

func (v NullableRestCommitMessageSuggestion) Get() *RestCommitMessageSuggestion {
	return v.value
}

func (v *NullableRestCommitMessageSuggestion) Set(val *RestCommitMessageSuggestion) {
	v.value = val
	v.isSet = true
}

func (v NullableRestCommitMessageSuggestion) IsSet() bool {
	return v.isSet
}

func (v *NullableRestCommitMessageSuggestion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestCommitMessageSuggestion(val *RestCommitMessageSuggestion) *NullableRestCommitMessageSuggestion {
	return &NullableRestCommitMessageSuggestion{value: val, isSet: true}
}

func (v NullableRestCommitMessageSuggestion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestCommitMessageSuggestion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


