/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 9.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RestCommentThreadDiffAnchor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestCommentThreadDiffAnchor{}

// RestCommentThreadDiffAnchor struct for RestCommentThreadDiffAnchor
type RestCommentThreadDiffAnchor struct {
	DiffType *string `json:"diffType,omitempty"`
	FileType *string `json:"fileType,omitempty"`
	FromHash *string `json:"fromHash,omitempty"`
	Line *int32 `json:"line,omitempty"`
	LineType *string `json:"lineType,omitempty"`
	MultilineMarker *RestCommentAnchorMultilineMarker `json:"multilineMarker,omitempty"`
	MultilineSpan *RestCommentAnchorMultilineSpan `json:"multilineSpan,omitempty"`
	Path *RestCommentAnchorPath `json:"path,omitempty"`
	PullRequest *RestCommentAnchorPullRequest `json:"pullRequest,omitempty"`
	SrcPath *RestCommentAnchorPath `json:"srcPath,omitempty"`
	ToHash *string `json:"toHash,omitempty"`
}

// NewRestCommentThreadDiffAnchor instantiates a new RestCommentThreadDiffAnchor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestCommentThreadDiffAnchor() *RestCommentThreadDiffAnchor {
	this := RestCommentThreadDiffAnchor{}
	return &this
}

// NewRestCommentThreadDiffAnchorWithDefaults instantiates a new RestCommentThreadDiffAnchor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestCommentThreadDiffAnchorWithDefaults() *RestCommentThreadDiffAnchor {
	this := RestCommentThreadDiffAnchor{}
	return &this
}

// GetDiffType returns the DiffType field value if set, zero value otherwise.
func (o *RestCommentThreadDiffAnchor) GetDiffType() string {
	if o == nil || IsNil(o.DiffType) {
		var ret string
		return ret
	}
	return *o.DiffType
}

// GetDiffTypeOk returns a tuple with the DiffType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestCommentThreadDiffAnchor) GetDiffTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DiffType) {
		return nil, false
	}
	return o.DiffType, true
}

// HasDiffType returns a boolean if a field has been set.
func (o *RestCommentThreadDiffAnchor) HasDiffType() bool {
	if o != nil && !IsNil(o.DiffType) {
		return true
	}

	return false
}

// SetDiffType gets a reference to the given string and assigns it to the DiffType field.
func (o *RestCommentThreadDiffAnchor) SetDiffType(v string) {
	o.DiffType = &v
}

// GetFileType returns the FileType field value if set, zero value otherwise.
func (o *RestCommentThreadDiffAnchor) GetFileType() string {
	if o == nil || IsNil(o.FileType) {
		var ret string
		return ret
	}
	return *o.FileType
}

// GetFileTypeOk returns a tuple with the FileType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestCommentThreadDiffAnchor) GetFileTypeOk() (*string, bool) {
	if o == nil || IsNil(o.FileType) {
		return nil, false
	}
	return o.FileType, true
}

// HasFileType returns a boolean if a field has been set.
func (o *RestCommentThreadDiffAnchor) HasFileType() bool {
	if o != nil && !IsNil(o.FileType) {
		return true
	}

	return false
}

// SetFileType gets a reference to the given string and assigns it to the FileType field.
func (o *RestCommentThreadDiffAnchor) SetFileType(v string) {
	o.FileType = &v
}

// GetFromHash returns the FromHash field value if set, zero value otherwise.
func (o *RestCommentThreadDiffAnchor) GetFromHash() string {
	if o == nil || IsNil(o.FromHash) {
		var ret string
		return ret
	}
	return *o.FromHash
}

// GetFromHashOk returns a tuple with the FromHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestCommentThreadDiffAnchor) GetFromHashOk() (*string, bool) {
	if o == nil || IsNil(o.FromHash) {
		return nil, false
	}
	return o.FromHash, true
}

// HasFromHash returns a boolean if a field has been set.
func (o *RestCommentThreadDiffAnchor) HasFromHash() bool {
	if o != nil && !IsNil(o.FromHash) {
		return true
	}

	return false
}

// SetFromHash gets a reference to the given string and assigns it to the FromHash field.
func (o *RestCommentThreadDiffAnchor) SetFromHash(v string) {
	o.FromHash = &v
}

// GetLine returns the Line field value if set, zero value otherwise.
func (o *RestCommentThreadDiffAnchor) GetLine() int32 {
	if o == nil || IsNil(o.Line) {
		var ret int32
		return ret
	}
	return *o.Line
}

// GetLineOk returns a tuple with the Line field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestCommentThreadDiffAnchor) GetLineOk() (*int32, bool) {
	if o == nil || IsNil(o.Line) {
		return nil, false
	}
	return o.Line, true
}

// HasLine returns a boolean if a field has been set.
func (o *RestCommentThreadDiffAnchor) HasLine() bool {
	if o != nil && !IsNil(o.Line) {
		return true
	}

	return false
}

// SetLine gets a reference to the given int32 and assigns it to the Line field.
func (o *RestCommentThreadDiffAnchor) SetLine(v int32) {
	o.Line = &v
}

// GetLineType returns the LineType field value if set, zero value otherwise.
func (o *RestCommentThreadDiffAnchor) GetLineType() string {
	if o == nil || IsNil(o.LineType) {
		var ret string
		return ret
	}
	return *o.LineType
}

// GetLineTypeOk returns a tuple with the LineType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestCommentThreadDiffAnchor) GetLineTypeOk() (*string, bool) {
	if o == nil || IsNil(o.LineType) {
		return nil, false
	}
	return o.LineType, true
}

// HasLineType returns a boolean if a field has been set.
func (o *RestCommentThreadDiffAnchor) HasLineType() bool {
	if o != nil && !IsNil(o.LineType) {
		return true
	}

	return false
}

// SetLineType gets a reference to the given string and assigns it to the LineType field.
func (o *RestCommentThreadDiffAnchor) SetLineType(v string) {
	o.LineType = &v
}

// GetMultilineMarker returns the MultilineMarker field value if set, zero value otherwise.
func (o *RestCommentThreadDiffAnchor) GetMultilineMarker() RestCommentAnchorMultilineMarker {
	if o == nil || IsNil(o.MultilineMarker) {
		var ret RestCommentAnchorMultilineMarker
		return ret
	}
	return *o.MultilineMarker
}

// GetMultilineMarkerOk returns a tuple with the MultilineMarker field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestCommentThreadDiffAnchor) GetMultilineMarkerOk() (*RestCommentAnchorMultilineMarker, bool) {
	if o == nil || IsNil(o.MultilineMarker) {
		return nil, false
	}
	return o.MultilineMarker, true
}

// HasMultilineMarker returns a boolean if a field has been set.
func (o *RestCommentThreadDiffAnchor) HasMultilineMarker() bool {
	if o != nil && !IsNil(o.MultilineMarker) {
		return true
	}

	return false
}

// SetMultilineMarker gets a reference to the given RestCommentAnchorMultilineMarker and assigns it to the MultilineMarker field.
func (o *RestCommentThreadDiffAnchor) SetMultilineMarker(v RestCommentAnchorMultilineMarker) {
	o.MultilineMarker = &v
}

// GetMultilineSpan returns the MultilineSpan field value if set, zero value otherwise.
func (o *RestCommentThreadDiffAnchor) GetMultilineSpan() RestCommentAnchorMultilineSpan {
	if o == nil || IsNil(o.MultilineSpan) {
		var ret RestCommentAnchorMultilineSpan
		return ret
	}
	return *o.MultilineSpan
}

// GetMultilineSpanOk returns a tuple with the MultilineSpan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestCommentThreadDiffAnchor) GetMultilineSpanOk() (*RestCommentAnchorMultilineSpan, bool) {
	if o == nil || IsNil(o.MultilineSpan) {
		return nil, false
	}
	return o.MultilineSpan, true
}

// HasMultilineSpan returns a boolean if a field has been set.
func (o *RestCommentThreadDiffAnchor) HasMultilineSpan() bool {
	if o != nil && !IsNil(o.MultilineSpan) {
		return true
	}

	return false
}

// SetMultilineSpan gets a reference to the given RestCommentAnchorMultilineSpan and assigns it to the MultilineSpan field.
func (o *RestCommentThreadDiffAnchor) SetMultilineSpan(v RestCommentAnchorMultilineSpan) {
	o.MultilineSpan = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *RestCommentThreadDiffAnchor) GetPath() RestCommentAnchorPath {
	if o == nil || IsNil(o.Path) {
		var ret RestCommentAnchorPath
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestCommentThreadDiffAnchor) GetPathOk() (*RestCommentAnchorPath, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *RestCommentThreadDiffAnchor) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given RestCommentAnchorPath and assigns it to the Path field.
func (o *RestCommentThreadDiffAnchor) SetPath(v RestCommentAnchorPath) {
	o.Path = &v
}

// GetPullRequest returns the PullRequest field value if set, zero value otherwise.
func (o *RestCommentThreadDiffAnchor) GetPullRequest() RestCommentAnchorPullRequest {
	if o == nil || IsNil(o.PullRequest) {
		var ret RestCommentAnchorPullRequest
		return ret
	}
	return *o.PullRequest
}

// GetPullRequestOk returns a tuple with the PullRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestCommentThreadDiffAnchor) GetPullRequestOk() (*RestCommentAnchorPullRequest, bool) {
	if o == nil || IsNil(o.PullRequest) {
		return nil, false
	}
	return o.PullRequest, true
}

// HasPullRequest returns a boolean if a field has been set.
func (o *RestCommentThreadDiffAnchor) HasPullRequest() bool {
	if o != nil && !IsNil(o.PullRequest) {
		return true
	}

	return false
}

// SetPullRequest gets a reference to the given RestCommentAnchorPullRequest and assigns it to the PullRequest field.
func (o *RestCommentThreadDiffAnchor) SetPullRequest(v RestCommentAnchorPullRequest) {
	o.PullRequest = &v
}

// GetSrcPath returns the SrcPath field value if set, zero value otherwise.
func (o *RestCommentThreadDiffAnchor) GetSrcPath() RestCommentAnchorPath {
	if o == nil || IsNil(o.SrcPath) {
		var ret RestCommentAnchorPath
		return ret
	}
	return *o.SrcPath
}

// GetSrcPathOk returns a tuple with the SrcPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestCommentThreadDiffAnchor) GetSrcPathOk() (*RestCommentAnchorPath, bool) {
	if o == nil || IsNil(o.SrcPath) {
		return nil, false
	}
	return o.SrcPath, true
}

// HasSrcPath returns a boolean if a field has been set.
func (o *RestCommentThreadDiffAnchor) HasSrcPath() bool {
	if o != nil && !IsNil(o.SrcPath) {
		return true
	}

	return false
}

// SetSrcPath gets a reference to the given RestCommentAnchorPath and assigns it to the SrcPath field.
func (o *RestCommentThreadDiffAnchor) SetSrcPath(v RestCommentAnchorPath) {
	o.SrcPath = &v
}

// GetToHash returns the ToHash field value if set, zero value otherwise.
func (o *RestCommentThreadDiffAnchor) GetToHash() string {
	if o == nil || IsNil(o.ToHash) {
		var ret string
		return ret
	}
	return *o.ToHash
}

// GetToHashOk returns a tuple with the ToHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestCommentThreadDiffAnchor) GetToHashOk() (*string, bool) {
	if o == nil || IsNil(o.ToHash) {
		return nil, false
	}
	return o.ToHash, true
}

// HasToHash returns a boolean if a field has been set.
func (o *RestCommentThreadDiffAnchor) HasToHash() bool {
	if o != nil && !IsNil(o.ToHash) {
		return true
	}

	return false
}

// SetToHash gets a reference to the given string and assigns it to the ToHash field.
func (o *RestCommentThreadDiffAnchor) SetToHash(v string) {
	o.ToHash = &v
}

func (o RestCommentThreadDiffAnchor) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestCommentThreadDiffAnchor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DiffType) {
		toSerialize["diffType"] = o.DiffType
	}
	if !IsNil(o.FileType) {
		toSerialize["fileType"] = o.FileType
	}
	if !IsNil(o.FromHash) {
		toSerialize["fromHash"] = o.FromHash
	}
	if !IsNil(o.Line) {
		toSerialize["line"] = o.Line
	}
	if !IsNil(o.LineType) {
		toSerialize["lineType"] = o.LineType
	}
	if !IsNil(o.MultilineMarker) {
		toSerialize["multilineMarker"] = o.MultilineMarker
	}
	if !IsNil(o.MultilineSpan) {
		toSerialize["multilineSpan"] = o.MultilineSpan
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.PullRequest) {
		toSerialize["pullRequest"] = o.PullRequest
	}
	if !IsNil(o.SrcPath) {
		toSerialize["srcPath"] = o.SrcPath
	}
	if !IsNil(o.ToHash) {
		toSerialize["toHash"] = o.ToHash
	}
	return toSerialize, nil
}

type NullableRestCommentThreadDiffAnchor struct {
	value *RestCommentThreadDiffAnchor
	isSet bool
}

func (v NullableRestCommentThreadDiffAnchor) Get() *RestCommentThreadDiffAnchor {
	return v.value
}

func (v *NullableRestCommentThreadDiffAnchor) Set(val *RestCommentThreadDiffAnchor) {
	v.value = val
	v.isSet = true
}

func (v NullableRestCommentThreadDiffAnchor) IsSet() bool {
	return v.isSet
}

func (v *NullableRestCommentThreadDiffAnchor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestCommentThreadDiffAnchor(val *RestCommentThreadDiffAnchor) *NullableRestCommentThreadDiffAnchor {
	return &NullableRestCommentThreadDiffAnchor{value: val, isSet: true}
}

func (v NullableRestCommentThreadDiffAnchor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestCommentThreadDiffAnchor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


