/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 9.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the SsoConfigEntity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SsoConfigEntity{}

// SsoConfigEntity struct for SsoConfigEntity
type SsoConfigEntity struct {
	DiscoveryRefreshCron *string `json:"discovery-refresh-cron,omitempty"`
	EnableAuthenticationFallback *bool `json:"enable-authentication-fallback,omitempty"`
	LastUpdated *time.Time `json:"last-updated,omitempty"`
	ShowLoginForm *bool `json:"show-login-form,omitempty"`
	ShowLoginFormForJsm *bool `json:"show-login-form-for-jsm,omitempty"`
}

// NewSsoConfigEntity instantiates a new SsoConfigEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSsoConfigEntity() *SsoConfigEntity {
	this := SsoConfigEntity{}
	return &this
}

// NewSsoConfigEntityWithDefaults instantiates a new SsoConfigEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSsoConfigEntityWithDefaults() *SsoConfigEntity {
	this := SsoConfigEntity{}
	return &this
}

// GetDiscoveryRefreshCron returns the DiscoveryRefreshCron field value if set, zero value otherwise.
func (o *SsoConfigEntity) GetDiscoveryRefreshCron() string {
	if o == nil || IsNil(o.DiscoveryRefreshCron) {
		var ret string
		return ret
	}
	return *o.DiscoveryRefreshCron
}

// GetDiscoveryRefreshCronOk returns a tuple with the DiscoveryRefreshCron field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SsoConfigEntity) GetDiscoveryRefreshCronOk() (*string, bool) {
	if o == nil || IsNil(o.DiscoveryRefreshCron) {
		return nil, false
	}
	return o.DiscoveryRefreshCron, true
}

// HasDiscoveryRefreshCron returns a boolean if a field has been set.
func (o *SsoConfigEntity) HasDiscoveryRefreshCron() bool {
	if o != nil && !IsNil(o.DiscoveryRefreshCron) {
		return true
	}

	return false
}

// SetDiscoveryRefreshCron gets a reference to the given string and assigns it to the DiscoveryRefreshCron field.
func (o *SsoConfigEntity) SetDiscoveryRefreshCron(v string) {
	o.DiscoveryRefreshCron = &v
}

// GetEnableAuthenticationFallback returns the EnableAuthenticationFallback field value if set, zero value otherwise.
func (o *SsoConfigEntity) GetEnableAuthenticationFallback() bool {
	if o == nil || IsNil(o.EnableAuthenticationFallback) {
		var ret bool
		return ret
	}
	return *o.EnableAuthenticationFallback
}

// GetEnableAuthenticationFallbackOk returns a tuple with the EnableAuthenticationFallback field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SsoConfigEntity) GetEnableAuthenticationFallbackOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableAuthenticationFallback) {
		return nil, false
	}
	return o.EnableAuthenticationFallback, true
}

// HasEnableAuthenticationFallback returns a boolean if a field has been set.
func (o *SsoConfigEntity) HasEnableAuthenticationFallback() bool {
	if o != nil && !IsNil(o.EnableAuthenticationFallback) {
		return true
	}

	return false
}

// SetEnableAuthenticationFallback gets a reference to the given bool and assigns it to the EnableAuthenticationFallback field.
func (o *SsoConfigEntity) SetEnableAuthenticationFallback(v bool) {
	o.EnableAuthenticationFallback = &v
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise.
func (o *SsoConfigEntity) GetLastUpdated() time.Time {
	if o == nil || IsNil(o.LastUpdated) {
		var ret time.Time
		return ret
	}
	return *o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SsoConfigEntity) GetLastUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastUpdated) {
		return nil, false
	}
	return o.LastUpdated, true
}

// HasLastUpdated returns a boolean if a field has been set.
func (o *SsoConfigEntity) HasLastUpdated() bool {
	if o != nil && !IsNil(o.LastUpdated) {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given time.Time and assigns it to the LastUpdated field.
func (o *SsoConfigEntity) SetLastUpdated(v time.Time) {
	o.LastUpdated = &v
}

// GetShowLoginForm returns the ShowLoginForm field value if set, zero value otherwise.
func (o *SsoConfigEntity) GetShowLoginForm() bool {
	if o == nil || IsNil(o.ShowLoginForm) {
		var ret bool
		return ret
	}
	return *o.ShowLoginForm
}

// GetShowLoginFormOk returns a tuple with the ShowLoginForm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SsoConfigEntity) GetShowLoginFormOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowLoginForm) {
		return nil, false
	}
	return o.ShowLoginForm, true
}

// HasShowLoginForm returns a boolean if a field has been set.
func (o *SsoConfigEntity) HasShowLoginForm() bool {
	if o != nil && !IsNil(o.ShowLoginForm) {
		return true
	}

	return false
}

// SetShowLoginForm gets a reference to the given bool and assigns it to the ShowLoginForm field.
func (o *SsoConfigEntity) SetShowLoginForm(v bool) {
	o.ShowLoginForm = &v
}

// GetShowLoginFormForJsm returns the ShowLoginFormForJsm field value if set, zero value otherwise.
func (o *SsoConfigEntity) GetShowLoginFormForJsm() bool {
	if o == nil || IsNil(o.ShowLoginFormForJsm) {
		var ret bool
		return ret
	}
	return *o.ShowLoginFormForJsm
}

// GetShowLoginFormForJsmOk returns a tuple with the ShowLoginFormForJsm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SsoConfigEntity) GetShowLoginFormForJsmOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowLoginFormForJsm) {
		return nil, false
	}
	return o.ShowLoginFormForJsm, true
}

// HasShowLoginFormForJsm returns a boolean if a field has been set.
func (o *SsoConfigEntity) HasShowLoginFormForJsm() bool {
	if o != nil && !IsNil(o.ShowLoginFormForJsm) {
		return true
	}

	return false
}

// SetShowLoginFormForJsm gets a reference to the given bool and assigns it to the ShowLoginFormForJsm field.
func (o *SsoConfigEntity) SetShowLoginFormForJsm(v bool) {
	o.ShowLoginFormForJsm = &v
}

func (o SsoConfigEntity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SsoConfigEntity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DiscoveryRefreshCron) {
		toSerialize["discovery-refresh-cron"] = o.DiscoveryRefreshCron
	}
	if !IsNil(o.EnableAuthenticationFallback) {
		toSerialize["enable-authentication-fallback"] = o.EnableAuthenticationFallback
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["last-updated"] = o.LastUpdated
	}
	if !IsNil(o.ShowLoginForm) {
		toSerialize["show-login-form"] = o.ShowLoginForm
	}
	if !IsNil(o.ShowLoginFormForJsm) {
		toSerialize["show-login-form-for-jsm"] = o.ShowLoginFormForJsm
	}
	return toSerialize, nil
}

type NullableSsoConfigEntity struct {
	value *SsoConfigEntity
	isSet bool
}

func (v NullableSsoConfigEntity) Get() *SsoConfigEntity {
	return v.value
}

func (v *NullableSsoConfigEntity) Set(val *SsoConfigEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableSsoConfigEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableSsoConfigEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSsoConfigEntity(val *SsoConfigEntity) *NullableSsoConfigEntity {
	return &NullableSsoConfigEntity{value: val, isSet: true}
}

func (v NullableSsoConfigEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSsoConfigEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


