/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 9.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RestPullRequestRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestPullRequestRef{}

// RestPullRequestRef struct for RestPullRequestRef
type RestPullRequestRef struct {
	DisplayId *string `json:"displayId,omitempty"`
	Id *string `json:"id,omitempty"`
	LatestCommit *string `json:"latestCommit,omitempty"`
	Repository *RestChangesetRepository `json:"repository,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewRestPullRequestRef instantiates a new RestPullRequestRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestPullRequestRef() *RestPullRequestRef {
	this := RestPullRequestRef{}
	return &this
}

// NewRestPullRequestRefWithDefaults instantiates a new RestPullRequestRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestPullRequestRefWithDefaults() *RestPullRequestRef {
	this := RestPullRequestRef{}
	return &this
}

// GetDisplayId returns the DisplayId field value if set, zero value otherwise.
func (o *RestPullRequestRef) GetDisplayId() string {
	if o == nil || IsNil(o.DisplayId) {
		var ret string
		return ret
	}
	return *o.DisplayId
}

// GetDisplayIdOk returns a tuple with the DisplayId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestPullRequestRef) GetDisplayIdOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayId) {
		return nil, false
	}
	return o.DisplayId, true
}

// HasDisplayId returns a boolean if a field has been set.
func (o *RestPullRequestRef) HasDisplayId() bool {
	if o != nil && !IsNil(o.DisplayId) {
		return true
	}

	return false
}

// SetDisplayId gets a reference to the given string and assigns it to the DisplayId field.
func (o *RestPullRequestRef) SetDisplayId(v string) {
	o.DisplayId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RestPullRequestRef) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestPullRequestRef) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RestPullRequestRef) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *RestPullRequestRef) SetId(v string) {
	o.Id = &v
}

// GetLatestCommit returns the LatestCommit field value if set, zero value otherwise.
func (o *RestPullRequestRef) GetLatestCommit() string {
	if o == nil || IsNil(o.LatestCommit) {
		var ret string
		return ret
	}
	return *o.LatestCommit
}

// GetLatestCommitOk returns a tuple with the LatestCommit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestPullRequestRef) GetLatestCommitOk() (*string, bool) {
	if o == nil || IsNil(o.LatestCommit) {
		return nil, false
	}
	return o.LatestCommit, true
}

// HasLatestCommit returns a boolean if a field has been set.
func (o *RestPullRequestRef) HasLatestCommit() bool {
	if o != nil && !IsNil(o.LatestCommit) {
		return true
	}

	return false
}

// SetLatestCommit gets a reference to the given string and assigns it to the LatestCommit field.
func (o *RestPullRequestRef) SetLatestCommit(v string) {
	o.LatestCommit = &v
}

// GetRepository returns the Repository field value if set, zero value otherwise.
func (o *RestPullRequestRef) GetRepository() RestChangesetRepository {
	if o == nil || IsNil(o.Repository) {
		var ret RestChangesetRepository
		return ret
	}
	return *o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestPullRequestRef) GetRepositoryOk() (*RestChangesetRepository, bool) {
	if o == nil || IsNil(o.Repository) {
		return nil, false
	}
	return o.Repository, true
}

// HasRepository returns a boolean if a field has been set.
func (o *RestPullRequestRef) HasRepository() bool {
	if o != nil && !IsNil(o.Repository) {
		return true
	}

	return false
}

// SetRepository gets a reference to the given RestChangesetRepository and assigns it to the Repository field.
func (o *RestPullRequestRef) SetRepository(v RestChangesetRepository) {
	o.Repository = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *RestPullRequestRef) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestPullRequestRef) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *RestPullRequestRef) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *RestPullRequestRef) SetType(v string) {
	o.Type = &v
}

func (o RestPullRequestRef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestPullRequestRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayId) {
		toSerialize["displayId"] = o.DisplayId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LatestCommit) {
		toSerialize["latestCommit"] = o.LatestCommit
	}
	if !IsNil(o.Repository) {
		toSerialize["repository"] = o.Repository
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableRestPullRequestRef struct {
	value *RestPullRequestRef
	isSet bool
}

func (v NullableRestPullRequestRef) Get() *RestPullRequestRef {
	return v.value
}

func (v *NullableRestPullRequestRef) Set(val *RestPullRequestRef) {
	v.value = val
	v.isSet = true
}

func (v NullableRestPullRequestRef) IsSet() bool {
	return v.isSet
}

func (v *NullableRestPullRequestRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestPullRequestRef(val *RestPullRequestRef) *NullableRestPullRequestRef {
	return &NullableRestPullRequestRef{value: val, isSet: true}
}

func (v NullableRestPullRequestRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestPullRequestRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


