/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 9.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RestMultilineCommentSpan type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestMultilineCommentSpan{}

// RestMultilineCommentSpan struct for RestMultilineCommentSpan
type RestMultilineCommentSpan struct {
	// The line number of the last line on the right-hand side of the diff that the comment spans
	DstSpanEnd *int32 `json:"dstSpanEnd,omitempty"`
	// The line number of the first line on the right-hand side of the diff that the comment spans
	DstSpanStart *int32 `json:"dstSpanStart,omitempty"`
	// The line number of the last line on the left-hand side of the diff that the comment spans
	SrcSpanEnd *int32 `json:"srcSpanEnd,omitempty"`
	// The line number of the first line on the left-hand side of the diff that the comment spans
	SrcSpanStart *int32 `json:"srcSpanStart,omitempty"`
}

// NewRestMultilineCommentSpan instantiates a new RestMultilineCommentSpan object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestMultilineCommentSpan() *RestMultilineCommentSpan {
	this := RestMultilineCommentSpan{}
	return &this
}

// NewRestMultilineCommentSpanWithDefaults instantiates a new RestMultilineCommentSpan object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestMultilineCommentSpanWithDefaults() *RestMultilineCommentSpan {
	this := RestMultilineCommentSpan{}
	return &this
}

// GetDstSpanEnd returns the DstSpanEnd field value if set, zero value otherwise.
func (o *RestMultilineCommentSpan) GetDstSpanEnd() int32 {
	if o == nil || IsNil(o.DstSpanEnd) {
		var ret int32
		return ret
	}
	return *o.DstSpanEnd
}

// GetDstSpanEndOk returns a tuple with the DstSpanEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestMultilineCommentSpan) GetDstSpanEndOk() (*int32, bool) {
	if o == nil || IsNil(o.DstSpanEnd) {
		return nil, false
	}
	return o.DstSpanEnd, true
}

// HasDstSpanEnd returns a boolean if a field has been set.
func (o *RestMultilineCommentSpan) HasDstSpanEnd() bool {
	if o != nil && !IsNil(o.DstSpanEnd) {
		return true
	}

	return false
}

// SetDstSpanEnd gets a reference to the given int32 and assigns it to the DstSpanEnd field.
func (o *RestMultilineCommentSpan) SetDstSpanEnd(v int32) {
	o.DstSpanEnd = &v
}

// GetDstSpanStart returns the DstSpanStart field value if set, zero value otherwise.
func (o *RestMultilineCommentSpan) GetDstSpanStart() int32 {
	if o == nil || IsNil(o.DstSpanStart) {
		var ret int32
		return ret
	}
	return *o.DstSpanStart
}

// GetDstSpanStartOk returns a tuple with the DstSpanStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestMultilineCommentSpan) GetDstSpanStartOk() (*int32, bool) {
	if o == nil || IsNil(o.DstSpanStart) {
		return nil, false
	}
	return o.DstSpanStart, true
}

// HasDstSpanStart returns a boolean if a field has been set.
func (o *RestMultilineCommentSpan) HasDstSpanStart() bool {
	if o != nil && !IsNil(o.DstSpanStart) {
		return true
	}

	return false
}

// SetDstSpanStart gets a reference to the given int32 and assigns it to the DstSpanStart field.
func (o *RestMultilineCommentSpan) SetDstSpanStart(v int32) {
	o.DstSpanStart = &v
}

// GetSrcSpanEnd returns the SrcSpanEnd field value if set, zero value otherwise.
func (o *RestMultilineCommentSpan) GetSrcSpanEnd() int32 {
	if o == nil || IsNil(o.SrcSpanEnd) {
		var ret int32
		return ret
	}
	return *o.SrcSpanEnd
}

// GetSrcSpanEndOk returns a tuple with the SrcSpanEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestMultilineCommentSpan) GetSrcSpanEndOk() (*int32, bool) {
	if o == nil || IsNil(o.SrcSpanEnd) {
		return nil, false
	}
	return o.SrcSpanEnd, true
}

// HasSrcSpanEnd returns a boolean if a field has been set.
func (o *RestMultilineCommentSpan) HasSrcSpanEnd() bool {
	if o != nil && !IsNil(o.SrcSpanEnd) {
		return true
	}

	return false
}

// SetSrcSpanEnd gets a reference to the given int32 and assigns it to the SrcSpanEnd field.
func (o *RestMultilineCommentSpan) SetSrcSpanEnd(v int32) {
	o.SrcSpanEnd = &v
}

// GetSrcSpanStart returns the SrcSpanStart field value if set, zero value otherwise.
func (o *RestMultilineCommentSpan) GetSrcSpanStart() int32 {
	if o == nil || IsNil(o.SrcSpanStart) {
		var ret int32
		return ret
	}
	return *o.SrcSpanStart
}

// GetSrcSpanStartOk returns a tuple with the SrcSpanStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestMultilineCommentSpan) GetSrcSpanStartOk() (*int32, bool) {
	if o == nil || IsNil(o.SrcSpanStart) {
		return nil, false
	}
	return o.SrcSpanStart, true
}

// HasSrcSpanStart returns a boolean if a field has been set.
func (o *RestMultilineCommentSpan) HasSrcSpanStart() bool {
	if o != nil && !IsNil(o.SrcSpanStart) {
		return true
	}

	return false
}

// SetSrcSpanStart gets a reference to the given int32 and assigns it to the SrcSpanStart field.
func (o *RestMultilineCommentSpan) SetSrcSpanStart(v int32) {
	o.SrcSpanStart = &v
}

func (o RestMultilineCommentSpan) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestMultilineCommentSpan) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DstSpanEnd) {
		toSerialize["dstSpanEnd"] = o.DstSpanEnd
	}
	if !IsNil(o.DstSpanStart) {
		toSerialize["dstSpanStart"] = o.DstSpanStart
	}
	if !IsNil(o.SrcSpanEnd) {
		toSerialize["srcSpanEnd"] = o.SrcSpanEnd
	}
	if !IsNil(o.SrcSpanStart) {
		toSerialize["srcSpanStart"] = o.SrcSpanStart
	}
	return toSerialize, nil
}

type NullableRestMultilineCommentSpan struct {
	value *RestMultilineCommentSpan
	isSet bool
}

func (v NullableRestMultilineCommentSpan) Get() *RestMultilineCommentSpan {
	return v.value
}

func (v *NullableRestMultilineCommentSpan) Set(val *RestMultilineCommentSpan) {
	v.value = val
	v.isSet = true
}

func (v NullableRestMultilineCommentSpan) IsSet() bool {
	return v.isSet
}

func (v *NullableRestMultilineCommentSpan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestMultilineCommentSpan(val *RestMultilineCommentSpan) *NullableRestMultilineCommentSpan {
	return &NullableRestMultilineCommentSpan{value: val, isSet: true}
}

func (v NullableRestMultilineCommentSpan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestMultilineCommentSpan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


