/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 9.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RestRefRestrictionCreate - версия RestRefRestriction для создания ограничений,
// где поле users сериализуется как массив строк (имен пользователей), а не объектов.
//
// API Bitbucket требует: {"users": ["admin"]}
// Вместо: {"users": [{"name": "admin", ...}]}
type RestRefRestrictionCreate struct {
	AccessKeys []RestSshAccessKey             `json:"accessKeys,omitempty"`
	Groups     []string                       `json:"groups,omitempty"`
	Id         *int32                         `json:"id,omitempty"`
	Matcher    *UpdatePullRequestCondition1RequestSourceMatcher `json:"matcher,omitempty"`
	Scope      *RestPullRequestConditionScope `json:"scope,omitempty"`
	Type       *string                        `json:"type,omitempty"`
	Users      []string                       `json:"users,omitempty"` // Строки вместо объектов
}

// NewRestRefRestrictionCreate creates a new RestRefRestrictionCreate
func NewRestRefRestrictionCreate() *RestRefRestrictionCreate {
	this := RestRefRestrictionCreate{}
	return &this
}

// NewRestRefRestrictionCreateWithDefaults creates a new RestRefRestrictionCreate with default values
func NewRestRefRestrictionCreateWithDefaults() *RestRefRestrictionCreate {
	this := RestRefRestrictionCreate{}
	return &this
}

// GetAccessKeys returns the AccessKeys field value if set, zero value otherwise.
func (o *RestRefRestrictionCreate) GetAccessKeys() []RestSshAccessKey {
	if o == nil || IsNil(o.AccessKeys) {
		var ret []RestSshAccessKey
		return ret
	}
	return o.AccessKeys
}

// GetAccessKeysOk returns a tuple with the AccessKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestRefRestrictionCreate) GetAccessKeysOk() ([]RestSshAccessKey, bool) {
	if o == nil || IsNil(o.AccessKeys) {
		return nil, false
	}
	return o.AccessKeys, true
}

// HasAccessKeys returns a boolean if a field has been set.
func (o *RestRefRestrictionCreate) HasAccessKeys() bool {
	if o != nil && !IsNil(o.AccessKeys) {
		return true
	}
	return false
}

// SetAccessKeys gets a reference to the given []RestSshAccessKey and assigns it to the AccessKeys field.
func (o *RestRefRestrictionCreate) SetAccessKeys(v []RestSshAccessKey) {
	o.AccessKeys = v
}

// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *RestRefRestrictionCreate) GetGroups() []string {
	if o == nil || IsNil(o.Groups) {
		var ret []string
		return ret
	}
	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestRefRestrictionCreate) GetGroupsOk() ([]string, bool) {
	if o == nil || IsNil(o.Groups) {
		return nil, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *RestRefRestrictionCreate) HasGroups() bool {
	if o != nil && !IsNil(o.Groups) {
		return true
	}
	return false
}

// SetGroups gets a reference to the given []string and assigns it to the Groups field.
func (o *RestRefRestrictionCreate) SetGroups(v []string) {
	o.Groups = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RestRefRestrictionCreate) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestRefRestrictionCreate) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RestRefRestrictionCreate) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}
	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *RestRefRestrictionCreate) SetId(v int32) {
	o.Id = &v
}

// GetMatcher returns the Matcher field value if set, zero value otherwise.
func (o *RestRefRestrictionCreate) GetMatcher() UpdatePullRequestCondition1RequestSourceMatcher {
	if o == nil || IsNil(o.Matcher) {
		var ret UpdatePullRequestCondition1RequestSourceMatcher
		return ret
	}
	return *o.Matcher
}

// GetMatcherOk returns a tuple with the Matcher field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestRefRestrictionCreate) GetMatcherOk() (*UpdatePullRequestCondition1RequestSourceMatcher, bool) {
	if o == nil || IsNil(o.Matcher) {
		return nil, false
	}
	return o.Matcher, true
}

// HasMatcher returns a boolean if a field has been set.
func (o *RestRefRestrictionCreate) HasMatcher() bool {
	if o != nil && !IsNil(o.Matcher) {
		return true
	}
	return false
}

// SetMatcher gets a reference to the given UpdatePullRequestCondition1RequestSourceMatcher and assigns it to the Matcher field.
func (o *RestRefRestrictionCreate) SetMatcher(v UpdatePullRequestCondition1RequestSourceMatcher) {
	o.Matcher = &v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *RestRefRestrictionCreate) GetScope() RestPullRequestConditionScope {
	if o == nil || IsNil(o.Scope) {
		var ret RestPullRequestConditionScope
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestRefRestrictionCreate) GetScopeOk() (*RestPullRequestConditionScope, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *RestRefRestrictionCreate) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}
	return false
}

// SetScope gets a reference to the given RestPullRequestConditionScope and assigns it to the Scope field.
func (o *RestRefRestrictionCreate) SetScope(v RestPullRequestConditionScope) {
	o.Scope = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *RestRefRestrictionCreate) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestRefRestrictionCreate) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *RestRefRestrictionCreate) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}
	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *RestRefRestrictionCreate) SetType(v string) {
	o.Type = &v
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *RestRefRestrictionCreate) GetUsers() []string {
	if o == nil || IsNil(o.Users) {
		var ret []string
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestRefRestrictionCreate) GetUsersOk() ([]string, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *RestRefRestrictionCreate) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}
	return false
}

// SetUsers gets a reference to the given []string and assigns it to the Users field.
func (o *RestRefRestrictionCreate) SetUsers(v []string) {
	o.Users = v
}

// MarshalJSON customizes the JSON serialization to ensure users is serialized as []string
func (o RestRefRestrictionCreate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccessKeys) {
		toSerialize["accessKeys"] = o.AccessKeys
	}
	if !IsNil(o.Groups) {
		toSerialize["groups"] = o.Groups
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Matcher) {
		toSerialize["matcher"] = o.Matcher
	}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users // []string вместо []RestApplicationUser
	}
	return json.Marshal(toSerialize)
}

type NullableRestRefRestrictionCreate struct {
	value *RestRefRestrictionCreate
	isSet bool
}

func (v NullableRestRefRestrictionCreate) Get() *RestRefRestrictionCreate {
	return v.value
}

func (v *NullableRestRefRestrictionCreate) Set(val *RestRefRestrictionCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableRestRefRestrictionCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableRestRefRestrictionCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestRefRestrictionCreate(val *RestRefRestrictionCreate) *NullableRestRefRestrictionCreate {
	return &NullableRestRefRestrictionCreate{value: val, isSet: true}
}

func (v NullableRestRefRestrictionCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestRefRestrictionCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
